services:
  api:
    build:
      context: .
      dockerfile: src/SilkHat.Api/Dockerfile
    ports:
      - "18080:8080"
    environment:
      - ConnectionStrings__SilkHat=Data Source=/data/silkhat.db
    volumes:
      - silkhat-data:/data
  ui:
    build:
      context: .
      dockerfile: src/SilkHat.Ui/Dockerfile
    depends_on:
      - api
    ports:
      - "10080:80"
volumes:
  silkhat-data:
