// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SilkHat.Infrastructure;

#nullable disable

namespace SilkHat.Infrastructure.Migrations
{
    [DbContext(typeof(SilkHatDbContext))]
    [Migration("20260109200526_AddDecisions")]
    partial class AddDecisions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SilkHat.Infrastructure.Entities.Decision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DecisionType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("DiscoveredUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RepositoryConfigId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ResolvedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SolutionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SubjectKey")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryConfigId", "SolutionId", "DecisionType", "SubjectKey")
                        .IsUnique();

                    b.ToTable("Decisions");
                });

            modelBuilder.Entity("SilkHat.Infrastructure.Entities.MethodImplementationDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImplementationMethodDocumentationId")
                        .HasColumnType("text");

                    b.Property<string>("ImplementationTypeDocumentationId")
                        .HasColumnType("text");

                    b.Property<string>("ImplementationTypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InterfaceMethodDocumentationId")
                        .HasColumnType("text");

                    b.Property<string>("InterfaceMethodSignature")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InterfaceTypeDocumentationId")
                        .HasColumnType("text");

                    b.Property<string>("InterfaceTypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RepositoryConfigId")
                        .HasColumnType("uuid");

                    b.Property<string>("SolutionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryConfigId", "SolutionId", "InterfaceMethodSignature")
                        .IsUnique();

                    b.ToTable("MethodImplementationDecisions");
                });

            modelBuilder.Entity("SilkHat.Infrastructure.Entities.RepositoryConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("RepositoryConfigs");
                });

            modelBuilder.Entity("SilkHat.Infrastructure.Entities.RepositoryGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("RepositoryGroups");
                });

            modelBuilder.Entity("SilkHat.Infrastructure.Entities.RepositorySolutionConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RepositoryConfigId")
                        .HasColumnType("uuid");

                    b.Property<string>("SolutionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryConfigId");

                    b.ToTable("RepositorySolutionConfigs");
                });

            modelBuilder.Entity("SilkHat.Infrastructure.Entities.RepositoryConfig", b =>
                {
                    b.HasOne("SilkHat.Infrastructure.Entities.RepositoryGroup", "Group")
                        .WithMany("RepositoryConfigs")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Group");
                });

            modelBuilder.Entity("SilkHat.Infrastructure.Entities.RepositorySolutionConfig", b =>
                {
                    b.HasOne("SilkHat.Infrastructure.Entities.RepositoryConfig", "RepositoryConfig")
                        .WithMany("Solutions")
                        .HasForeignKey("RepositoryConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RepositoryConfig");
                });

            modelBuilder.Entity("SilkHat.Infrastructure.Entities.RepositoryConfig", b =>
                {
                    b.Navigation("Solutions");
                });

            modelBuilder.Entity("SilkHat.Infrastructure.Entities.RepositoryGroup", b =>
                {
                    b.Navigation("RepositoryConfigs");
                });
#pragma warning restore 612, 618
        }
    }
}
