// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SilkHat.Infrastructure;

#nullable disable

namespace SilkHat.Infrastructure.Migrations
{
    [DbContext(typeof(SilkHatDbContext))]
    [Migration("20260106081530_AddRepositorySolutionConfigs")]
    partial class AddRepositorySolutionConfigs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SilkHat.Infrastructure.Entities.RepositoryConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("RepositoryConfigs");
                });

            modelBuilder.Entity("SilkHat.Infrastructure.Entities.RepositoryGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RepositoryGroups");
                });

            modelBuilder.Entity("SilkHat.Infrastructure.Entities.RepositorySolutionConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RepositoryConfigId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryConfigId");

                    b.ToTable("RepositorySolutionConfigs");
                });

            modelBuilder.Entity("SilkHat.Infrastructure.Entities.RepositoryConfig", b =>
                {
                    b.HasOne("SilkHat.Infrastructure.Entities.RepositoryGroup", "Group")
                        .WithMany("RepositoryConfigs")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Group");
                });

            modelBuilder.Entity("SilkHat.Infrastructure.Entities.RepositorySolutionConfig", b =>
                {
                    b.HasOne("SilkHat.Infrastructure.Entities.RepositoryConfig", "RepositoryConfig")
                        .WithMany("Solutions")
                        .HasForeignKey("RepositoryConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RepositoryConfig");
                });

            modelBuilder.Entity("SilkHat.Infrastructure.Entities.RepositoryConfig", b =>
                {
                    b.Navigation("Solutions");
                });

            modelBuilder.Entity("SilkHat.Infrastructure.Entities.RepositoryGroup", b =>
                {
                    b.Navigation("RepositoryConfigs");
                });
#pragma warning restore 612, 618
        }
    }
}
