// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SilkHat.Infrastructure;

#nullable disable

namespace SilkHat.Infrastructure.Migrations
{
    [DbContext(typeof(SilkHatDbContext))]
    [Migration("20260106081500_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");
            modelBuilder.HasAnnotation("Relational:MaxIdentifierLength", 63);
            modelBuilder.HasAnnotation("Npgsql:PostgresVersion", new Version(18, 0));

            modelBuilder.Entity("SilkHat.Infrastructure.Entities.RepositoryConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("RepositoryConfigs");
                });

            modelBuilder.Entity("SilkHat.Infrastructure.Entities.RepositoryGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("RepositoryGroups");
                });

            modelBuilder.Entity("SilkHat.Infrastructure.Entities.RepositoryConfig", b =>
                {
                    b.HasOne("SilkHat.Infrastructure.Entities.RepositoryGroup", "Group")
                        .WithMany("RepositoryConfigs")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Group");
                });

            modelBuilder.Entity("SilkHat.Infrastructure.Entities.RepositoryGroup", b =>
                {
                    b.Navigation("RepositoryConfigs");
                });
#pragma warning restore 612, 618
        }
    }
}
