<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.11" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SilkHat.Infrastructure\SilkHat.Infrastructure.csproj" />
    <ProjectReference Include="..\SilkHat.Core\SilkHat.Core.csproj" />
    <ProjectReference Include="..\SilkHat.Analysis\SilkHat.Analysis.csproj" />
    <ProjectReference Include="..\SilkHat.Code.Analysis\SilkHat.Code.Analysis.csproj" />
    <ProjectReference Include="..\SilkHat.Code.Core\SilkHat.Code.Core.csproj" />
  </ItemGroup>

</Project>
